#define COMPLETE 100
#define MOVE_STOP 0
#define MOVE_FORWARD 1
#define MOVE_FORWARD_HALF 2
#define MOVE_BACK 3
#define MOVE_BACK_HALF 4
#define MOVE_ACW 5
#define CURVE_ACW 6
#define MOVE_CW 7
#define CURVE_CW 8
